"""Private native protocol; public callers should use the Python modules."""

class JoseError(ValueError): ...
class InvalidJWKValue(JoseError): ...
class InvalidJWSObject(JoseError): ...
class InvalidJWSSignature(JoseError): ...
class InvalidJWEData(JoseError): ...
class JWTExpired(JoseError): ...
class JWTNotYetValid(JoseError): ...
class JWTInvalidClaimValue(JoseError): ...
class UnsupportedAlgorithm(JoseError): ...
POST_QUANTUM: bool
PKCS11: bool
LEGACY: bool
MAX_TOKEN_BYTES: int

def key_normalize(s: str, validate: bool) -> str: ...
def key_generate(kty: str, size: int, crv: str, alg: str) -> str: ...
def key_public(s: str) -> str: ...
def key_thumbprint(s: str) -> str: ...
def key_import(data: bytes, private: bool) -> str: ...
def key_export(s: str, private: bool) -> bytes: ...
def sign(s: str, payload: bytes, protected: str, unprotected: str | None,
         detached: bool, understood: list[str], allow_key_reference_headers: bool = False) -> str: ...
def verify(s: str, token: str, detached: bytes | None, understood: list[str]) -> bytes: ...
def encrypt(s: str, payload: bytes, protected: str, allow_key_reference_headers: bool = False) -> str: ...
def decrypt(s: str, token: str, alg: str) -> bytes: ...
def validate_claims(claims: str, header: str, options: str) -> None: ...
def certificate(action: str, header: str, der: bytes) -> str: ...

class Pkcs11Provider:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def with_token(path: str, label: str, serial: str | None = None) -> Pkcs11Provider: ...
    @staticmethod
    def with_slot_id(path: str, slot_id: int) -> Pkcs11Provider: ...
    @property
    def slot_id(self) -> int: ...
    def open_session(self, pin: str) -> Pkcs11Session: ...

class Pkcs11Session: ...

class Pkcs11Signer:
    def __init__(self, session: Pkcs11Session, label: str, alg: str) -> None: ...
    def _sign(self, payload: bytes, protected: str, unprotected: str | None,
              detached: bool, understood: list[str], allow_key_reference_headers: bool = False) -> str: ...

class Pkcs11Verifier:
    def __init__(self, session: Pkcs11Session, label: str, alg: str) -> None: ...
    def _verify(self, token: str, detached: bytes | None, understood: list[str]) -> bytes: ...
